apiVersion: v1
kind: Service
metadata:
  name: store-v1
  annotations:
    argocd.argoproj.io/tracking-id: app:store/Deployment:default/store-v1
spec:
  selector:
    app: store
    version: v1
  ports:
  - port: 8080
    targetPort: 8080
